package.json, src/components/popover/popover.js, src/components/popover/popover.scss, src/components/portal/portal.js, yarn.lock
=> GVP-265 Add popover

src/components/chip/chip.scss
=> GVP-271 fix background

public/locales/en/translations.json, src/modules/password-change/password-change-form.js, src/modules/password-change/password-change.js, src/modules/password-change/password-change.scss, src/pages/profile/password/password.page.js, src/pages/profile/profile.routes.js, src/pages/profile/settings/settings.page.js, src/pages/profile/settings/settings.scss
=> GVW-29 Profile: change password

public/locales/en/translations.json, src/modules/2fa/2fa-container.js, src/modules/2fa/google-auth/generate-recovery-codes/generate-recovery-codes.js, src/modules/2fa/google-auth/generate-recovery-codes/generate-recovery-form.js, src/modules/2fa/google-auth/google-auth-codes.js
=> GVP-289 add recovery codes

src/shared/utils/validators/validators.js
=> attempt to remove the pain

src/components/avatar/profile-avatar/profile-avatar.scss, src/components/chip/chip.scss, src/components/gv-datepicker/gv-datepicker.js, src/components/gv-datepicker/gv-datepicker.scss, src/components/navigation/navigation.scss, src/components/notifications-widget/notifications-widget.js, src/components/notifications-widget/notifications-widget.scss, src/components/popover/popover.js, src/components/popover/popover.scss, src/components/profile-widget/profile-widget.scss, src/components/select/select.js, src/modules/header/components/header.js, src/pages/app/components/notifications/components/notifications.js, src/pages/app/components/notifications/components/notifications.scss, src/pages/dashboard/components/dashboard-portfolio-chart-section/dashboard-in-requests/dashboard-in-requests-container.js, src/pages/dashboard/components/dashboard-portfolio-chart-section/dashboard-in-requests/dashboard-in-requests.scss, src/shared/media/event-ended-red.svg, src/shared/modules/alert-message/components/alert-message-list/alert-message-list.scss, src/styles/_constants.scss
=> GVW-85 Bug fuxing / tooltip bug

.prettierrc
=> GVW-172 prettier sass fix

packages/investor/public/locales/en/translations.json, packages/manager/public/locales/en/translations.json, packages/shared/components/dashboard/dashboard-assets/dashboard-funds/dashboard-funds.js, packages/shared/components/dashboard/dashboard.constants.js, packages/shared/components/funds-table/funds-table.scss
=> GVW-174 add value to funds table in dashboard

packages/shared/components/details/details-description-section/details-investment/details-investment.js, packages/shared/components/details/details-description-section/details-investment/details-investment.scss
=> GVW-175 Remove "invested" and "profit" from Fund details

packages/investor/src/pages/app/components/app-layout/app-layout.js, packages/investor/src/pages/app/components/app-layout/app-layout.scss, packages/investor/src/root.js, packages/manager/src/pages/app/components/app-layout/app-layout.js, packages/manager/src/pages/app/components/app-layout/app-layout.scss, packages/manager/src/root.js, packages/shared/components/modal/modal.scss, packages/shared/styles/index.scss
=> GV-50 fix modals

packages/investor/src/pages/app/components/app-layout/app-layout.scss, packages/manager/src/pages/app/components/app-layout/app-layout.scss
=> GV-50 fix app style

packages/investor/package.json, packages/manager/package.json, packages/shared/modules/alert-message/components/alert-message-list/alert-message-list.js, packages/shared/modules/alert-message/components/alert-message-list/alert-message.js, yarn.lock
=> GV-74 add animations for alerts

packages/shared/components/table/components/table-toolbar.js, packages/shared/components/table/components/table.js, packages/shared/components/table/components/table.scss
Added the condition for render non-empty filters in the tables
=> fixed the empty filters in the tables

packages/shared/modules/programs-table/components/programs-table/program-table-row-short.js
=> GV-104 add stopPropagation for program links in table

packages/investor/src/pages/dashboard/components/dashboard-portfolio-chart-section/dashboard-portfolio-chart-section.scss, packages/manager/src/pages/dashboard/components/dashboard-portfolio-chart-section/dashboard-portfolio-chart-section.scss, packages/manager/src/pages/dashboard/components/dashboard-portfolio-events/dashboard-portfolio-events.scss, packages/shared/components/dashboard/dashboard-portfolio-events/dashboard-portfolio-events.scss, packages/shared/components/details/details-description-section/details-statistic-section/details-history/details-history.scss, packages/shared/components/global-search/components/global-search-result/global-search-input.scss, packages/shared/components/programs-rating/programs-rating.scss, packages/shared/components/surface/surface.scss, packages/shared/components/table/components/filtering/filter.scss, packages/shared/components/table/components/table.scss, packages/shared/modules/programs-table/components/programs-table/programs.scss, packages/shared/styles/_sizes.scss
Fixed the horizontal paddings in the tables and some styles bugs
=> Ratings facet fix styles

packages/investor/src/pages/app/components/app-layout/app-layout.scss, packages/investor/src/pages/dashboard/components/dashboard-portfolio-chart-section/dashboard-portfolio-chart-section.scss, packages/manager/src/pages/app/components/app-layout/app-layout.scss, packages/manager/src/pages/dashboard/components/dashboard-portfolio-chart-section/dashboard-chart-assets/dashboard-chart-assets.scss, packages/manager/src/pages/dashboard/components/dashboard-portfolio-chart-section/dashboard-portfolio-chart-section.scss, packages/shared/components/dashboard/dashboard-assets/dashboard-assets.scss, packages/shared/components/dashboard/dashboard-portfolio-chart-section/dashboard-in-requests/dashboard-in-requests.scss, packages/shared/components/manager/manager-history/manager-history.scss
FIxed the styles for app-layout and some horizontal paddings in the surfaces
=> Rating facet fix styles 2

packages/manager/public/locales/en/translations.json, packages/manager/src/pages/create-fund/components/create-fund-settings/create-fund-settings.js, packages/manager/src/pages/create-fund/components/create-fund-settings/create-fund-settings.validators.js, packages/manager/src/pages/create-fund/create-fund.container.js, packages/manager/src/pages/create-fund/services/create-fund.service.js, packages/manager/src/pages/create-program/components/create-program-settings/create-program-settings.js, packages/manager/src/pages/create-program/create-program.container.js, packages/manager/src/pages/create-program/services/create-program.service.js
=> GV-77 fund name validation

packages/shared/components/program-withdraw/program-withdraw-enter-amount-step.js
=> Add formatCurrencyValue to account currency in program withdraw 

packages/shared/components/dashboard/dashboard-assets/dashboard-assets.scss, packages/shared/components/dashboard/dashboard-assets/dashboard-programs/dashboard-programs.js, packages/shared/components/programs-rating/programs-rating.scss, packages/shared/components/table/components/table.scss, packages/shared/styles/_colors.scss
Updated the colors for pretender programs in the tables and added the pretender programs in the table of dashboard
=> Rating facet  update style tables

packages/investor/public/index.html, packages/manager/public/index.html
Changed theme-color from turquoise to dark
=> GV-175 updated the theme-color for android

packages/shared/components/funds/fund-details/fund-details-description/fund-details-description.js
=> Revert "hide close fund button"

packages/shared/components/deposit/deposit-form.js, packages/shared/components/deposit/deposit-popup.js
I deleted the prop "disabled" in the DepositPopup component. Or should this prop be included in the condition in the deposit form?
=> GV-297 added the conditions of the disabled submit button in the deposit form

packages/shared/components/deposit/deposit-form.js
not more then the amount of available to invest
=> GV-374 fixed the bug to allow input in the form the amount

packages/shared/components/wallet/components/wallet-currency.tsx, packages/shared/components/wallet/components/wallet-settings/wallet-settings-container.js, packages/shared/components/wallet/components/wallet-settings/wallet-settings.js, packages/shared/components/wallet/components/wallet-total.tsx, packages/shared/components/wallet/services/wallet.services.js
added the flag off/on payment fee with GVT from api
=> GV-540 updated the component of wallet-settings

packages/shared/components/wallet/components/wallet-settings/wallet-settings-container.js
removed the success message and added error message for switching of wallet settings
=> removed the success message and added error message

packages/shared/components/wallet/components/wallet-transactions/all-transactions-row.tsx
As part of this task I did to the GV-610 task.
=> GV-600 fixed amount column in the all transactions table

packages/investor/src/pages/dashboard/components/dashboard-portfolio-chart-section/dashboard-chart/dashboard-portfoio-tooltip.js, packages/investor/src/pages/dashboard/components/dashboard-portfolio-chart-section/dashboard-chart/dashboard-portfolio-chart-stat.js
Fixed the bug in the another components
=> Bug 612 add float numbers dashboard chart

packages/shared/components/hint/hint.test.tsx, packages/shared/components/hint/hint.tsx
I'm not sure that this test are complete
=> added the tests for the component Hint

packages/shared/components/facet-container/facet-container.tsx, packages/shared/components/funds/funds-facet/components/funds-facet-table.tsx, packages/shared/components/funds/funds-facet/components/funds-facet.constants.ts, packages/shared/components/programs/programs-facet/components/programs-facet-table.tsx, packages/shared/components/programs/programs-facet/components/programs-facet.constants.ts, packages/shared/components/table/components/filtering/date-range-filter/date-range-filter.helpers.ts
=> Use sorting and filtering values from the server

packages/shared/components/details/details-description-section/details-investment/details-investment.tsx, packages/shared/components/portfolio-events-table/portfolio-events-table.constants.ts, packages/shared/components/portfolio-events-table/portfolio-events-table.tsx, packages/shared/locales/en/translations.json
=> GV-1489 Update rules for Fee availability in the Event

packages/social-trader/src/pages/accounts/account-details/account-details.loader-data.ts, packages/social-trader/src/pages/dashboard/dashboard.loaders-data.ts, packages/social-trader/src/pages/landing-page/components/broker-info/broker-info.tsx, packages/social-trader/src/pages/landing-page/components/events-list/event-last-item.tsx, packages/social-trader/src/pages/landing-page/components/first-slider/first-slifer.tsx, packages/social-trader/src/pages/landing-page/components/info-list/info-item.tsx, packages/social-trader/src/pages/landing-page/components/join-button.tsx, packages/social-trader/src/pages/landing-page/components/lp-button/lp-button.scss, packages/social-trader/src/pages/landing-page/components/lp-button/lp-button.tsx, packages/social-trader/src/pages/landing-page/components/lp-header/lp-header.tsx, packages/social-trader/src/pages/landing-page/containers/advantages-container/advantages-container.tsx, packages/social-trader/src/pages/landing-page/containers/follows-container/follows-container.tsx, packages/social-trader/src/pages/landing-page/containers/funds-container/funds-container.tsx, packages/social-trader/src/pages/landing-page/containers/programs-container/programs-container.tsx
Add events from press join button
=> Join button

packages/social-trader/src/pages/landing-page/static-data/faq.tsx
=> Update some content on FAQ page

packages/social-trader/src/components/assets/asset.helpers.ts
This reverts commit d8e7541724e9a53bc93f1701e7b5caaca6bd460d.
=> Revert "Change checks for if-modified-since"
